version: '2'
services:
  web:
    build: ./docker/web
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./:/app
    environment:
      BUNDLE_PATH: vendor/bundle
    # command: bundle exec bin/rails s --bind 0.0.0.0 --port 3000
    command: tail -f /dev/null

  db:
    build: ./docker/db

  nodejs:
    build: ./docker/nodejs
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links:
      - web
